<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%rayon}}`.
 */
class m201207_115631_create_rayon_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%rayon}}', [
            'id' => $this->primaryKey(),
            'url' => $this->string(75),
            'value' => $this->string(75),
            'city_id' => $this->tinyInteger(),
            'value2' => $this->string(45),
            'value3' => $this->string(45),
        ]);

        $this->execute(
            "INSERT INTO `rayon` ( `url`, `value`, `city_id`, `value2`, `value3`) VALUES
( 'biryulevo-vostochnoe', 'Бирюлево Восточное', 1, 'Бирюлево Восточное', NULL),
( 'biryulevo-zapadnoe', 'Бирюлево Западное', 1, 'Бирюлево Западное', NULL),
( 'veshnyaki', 'Вешняки', 1, 'Вешняков', NULL),
( 'vnukovo', 'Внуково', 1, 'Внуково', NULL),
( 'vostochnyy', 'Восточный', 1, 'Восточном', NULL),
( 'degunino-vostochnoe', 'Дегунино Восточное', 1, 'Дегунино Восточное', NULL),
( 'degunino-zapadnoe', 'Дегунино Западное', 1, 'Дегунино Западное', NULL),
( 'desenovskoe', 'Десеновское', 1, 'Десеновском', NULL),
( 'ivanovskoe', 'Ивановское', 1, 'Ивановском', NULL),
( 'kapotnya', 'Капотня', 1, 'Капотни', NULL),
( 'kokoshkino', 'Кокошкино', 1, 'Кокошкино', NULL),
( 'kosino-uhtomskiy', 'Косино-Ухтомский', 1, 'Косино-Ухтомском', NULL),
( 'kotlovka', 'Котловка', 1, 'Котловки', NULL),
( 'kryukovo', 'Крюково', 1, 'Крюково', NULL),
( 'kurkino', 'Куркино', 1, 'Куркино', NULL),
( 'lianozovo', 'Лианозово', 1, 'Лианозово', NULL),
( 'losinoostrovskiy', 'Лосиноостровский', 1, 'Лосиноостровском', NULL),
( 'marfino', 'Марфино', 1, 'Марфино', NULL),
( 'matushkino', 'Матушкино', 1, 'Матушкино', NULL),
( 'medvedkovo-yughnoe', 'Медведково Южное', 1, 'Медведково Южное', NULL),
( 'metrogorodok', 'Метрогородок', 1, 'Метрогородка', NULL),
( 'mihaylovo-yarcevskoe', 'Михайлово-Ярцевское', 1, 'Михайлово-Ярцевское', NULL),
( 'moghayskiy', 'Можайский', 1, 'Можайском', NULL),
( 'molghaninovskiy', 'Молжаниновский', 1, 'Молжаниновском', NULL),
( 'moskvorechye-saburovo', 'Москворечье-Сабурово', 1, 'Москворечье-Сабурово', NULL),
( 'mosrentgen', 'Мосрентген', 1, 'Мосрентгена', NULL),
( 'nekrasovka', 'Некрасовка', 1, 'Некрасовке', NULL),
( 'novo-peredelkino', 'Ново-Переделкино', 1, 'Ново-Переделкино', NULL),
( 'novofedorovskoe', 'Новофедоровское', 1, 'Новофедоровское', NULL),
( 'ochakovo-matveevskoe', 'Очаково-Матвеевское', 1, 'Очаково-Матвеевском', NULL),
( 'pervomayskoe', 'Первомайское', 1, 'Первомайском', NULL),
( 'rogovskoe', 'Роговское', 1, 'Роговском', NULL),
( 'ryazanovskoe', 'Рязановское', 1, 'Рязановском', NULL),
( 'savelki', 'Савелки', 1, 'Савелках', NULL),
( 'severnoe-tushino', 'Северное Тушино', 1, 'Северном Тушино', NULL),
( 'silino', 'Силино', 1, 'Силино', NULL),
( 'solncevo', 'Солнцево', 1, 'Солнцево', NULL),
( 'sosenskoe', 'Сосенское', 1, 'Сосенском', NULL),
( 'staroe-kryukovo', 'Старое Крюково', 1, 'Старом Крюково', NULL),
( 'troick', 'Троицк', 1, 'Троицком', NULL),
( 'filimonkovskoe', 'Филимонковское', 1, 'Филимонковском', NULL),
( 'horoshevo-mnevniki', 'Хорошево-Мневники', 1, 'Хорошево-Мневники', NULL),
( 'schapovskoe', 'Щаповское', 1, 'Щаповскоом', NULL),
( 'scherbinka', 'Щербинка', 1, 'Щербинке', NULL),
( 'yughnoe-tushino', 'Южное Тушино', 1, 'Южное Тушино', NULL),
( 'yaroslavskiy', 'Ярославский', 1, 'Ярославском', NULL),
( 'akademicheskiy', 'Академический', 1, 'Академическом', NULL),
( 'alekseevskiy', 'Алексеевский', 1, 'Алексеевском', NULL),
( 'arbat', 'Арбат', 1, 'Арбата', NULL),
( 'aeroport', 'Аэропорт', 1, 'Аэропорта', NULL),
( 'babushkinskiy', 'Бабушкинский', 1, 'Бабушкинском', NULL),
( 'basmannyy', 'Басманный', 1, 'Басманном', NULL),
( 'beskudnikovskiy', 'Бескудниковский', 1, 'Бескудниковском', NULL),
( 'bibirevo', 'Бибирево', 1, 'Бибирево', NULL),
( 'bogorodskoe', 'Богородское', 1, 'Богородском', NULL),
( 'brateevo', 'Братеево', 1, 'Братеево', NULL),
( 'butovo-severnoe', 'Бутово Северное', 1, 'Бутово Северное', NULL),
( 'butovo-yughnoe', 'Бутово Южное', 1, 'Бутово Южное', NULL),
( 'butyrskiy', 'Бутырский', 1, 'Бутырском', NULL),
( 'voykovskiy', 'Войковский', 1, 'Войковском', NULL),
( 'vyhino-ghulebino', 'Выхино-Жулебино', 1, 'Выхино-Жулебино', NULL),
( 'gagarinskiy', 'Гагаринский', 1, 'Гагаринском', NULL),
( 'golovinskiy', 'Головинский', 1, 'Головинском', NULL),
( 'golyyanovo', 'Гольяново', 1, 'Гольяново', NULL),
( 'danilovskiy', 'Даниловский', 1, 'Даниловском', NULL),
( 'donskoy', 'Донской', 1, 'Донском', NULL),
( 'dorogomilovo', 'Дорогомилово', 1, 'Дорогомилово', NULL),
( 'zamoskvorechye', 'Замоскворечье', 1, 'Замоскворечье', NULL),
( 'zyuzino', 'Зюзино', 1, 'Зюзино', NULL),
( 'zyablikovo', 'Зябликово', 1, 'Зябликово', NULL),
( 'izmaylovo', 'Измайлово', 1, 'Измайлово', NULL),
( 'izmaylovo-severnoe', 'Измайлово Северное', 1, 'Измайлово Северное', NULL),
( 'konykovo', 'Коньково', 1, 'Коньково', NULL),
( 'koptevo', 'Коптево', 1, 'Коптево', NULL),
( 'krasnogorsk', 'Красногорск', 1, 'Красногорском', NULL),
( 'krasnoselyskiy', 'Красносельский', 1, 'Красносельском', NULL),
( 'krylatskoe', 'Крылатское', 1, 'Крылатском', NULL),
( 'kuzyminki', 'Кузьминки', 1, 'Кузьминок', NULL),
( 'kuncevo', 'Кунцево', 1, 'Кунцево', NULL),
( 'levobereghnyy', 'Левобережный', 1, 'Левобережном', NULL),
( 'lefortovo', 'Лефортово', 1, 'Лефортово', NULL),
( 'lyublino', 'Люблино', 1, 'Люблино', NULL),
( 'maryina-roscha', 'Марьина Роща', 1, 'Марьиной Рощи', NULL),
( 'maryino', 'Марьино', 1, 'Марьино', NULL),
( 'medvedkovo-severnoe', 'Медведково Северное', 1, 'Медведково Северное', NULL),
( 'meschanskiy', 'Мещанский', 1, 'Мещанском', NULL),
( 'mitino', 'Митино', 1, 'Митино', NULL),
( 'moskovskiy', 'Московский', 1, 'Московском', NULL),
( 'nagatino-sadovniki', 'Нагатино-Садовники', 1, 'Нагатино-Садовники', NULL),
( 'nagatinskiy-zaton', 'Нагатинский Затон', 1, 'Нагатинском Затоне', NULL),
( 'nagornyy', 'Нагорный', 1, 'Нагорном', NULL),
( 'nighegorodskiy', 'Нижегородский', 1, 'Нижегородском', NULL),
( 'novogireevo', 'Новогиреево', 1, 'Новогиреево', NULL),
( 'novokosino', 'Новокосино', 1, 'Новокосино', NULL),
( 'obruchevskiy', 'Обручевский', 1, 'Обручевском', NULL),
( 'orehovo-borisovo-severnoe', 'Орехово-Борисово Северное', 1, 'Орехово-Борисово Северное', NULL),
( 'orehovo-borisovo-yughnoe', 'Орехово-Борисово Южное', 1, 'Орехово-Борисово Южное', NULL),
( 'ostankinskiy', 'Останкинский', 1, 'Останкинском', NULL),
( 'otradnoe', 'Отрадное', 1, 'Отрадном', NULL),
( 'perovo', 'Перово', 1, 'Перово', NULL),
( 'pechatniki', 'Печатники', 1, 'Печатниках', NULL),
( 'pokrovskoe-streshnevo', 'Покровское-Стрешнево', 1, 'Покровское-Стрешнево', NULL),
( 'preobraghenskoe', 'Преображенское', 1, 'Преображенском', NULL),
( 'presnenskiy', 'Пресненский', 1, 'Пресненском', NULL),
( 'prospekt-vernadskogo', 'Проспект Вернадского', 1, 'Проспект Вернадского', NULL),
( 'ramenki', 'Раменки', 1, 'Раменках', NULL),
( 'rostokino', 'Ростокино', 1, 'Ростокино', NULL),
( 'ryazanskiy', 'Рязанский', 1, 'Рязанском', NULL),
( 'savelovskiy', 'Савеловский', 1, 'Савеловском', NULL),
( 'sviblovo', 'Свиблово', 1, 'Свиблово', NULL),
( 'sokol', 'Сокол', 1, 'Сокол', NULL),
( 'sokolinaya-gora', 'Соколиная Гора', 1, 'Соколиная Гора', NULL),
( 'sokolyniki', 'Сокольники', 1, 'Сокольниках', NULL),
( 'strogino', 'Строгино', 1, 'Строгино', NULL),
( 'taganskiy', 'Таганский', 1, 'Таганском', NULL),
( 'tverskoy', 'Тверской', 1, 'Тверском', NULL),
( 'tekstilyschiki', 'Текстильщики', 1, 'Текстильщиках', NULL),
( 'timiryazevskiy', 'Тимирязевский', 1, 'Тимирязевском', NULL),
( 'troparevo-nikulino', 'Тропарево-Никулино', 1, 'Тропарево-Никулино', NULL),
( 'tushino-severnoe', 'Тушино Северное', 1, 'Тушино Северное', NULL),
( 'tushino-yughnoe', 'Тушино Южное', 1, 'Тушино Южное', NULL),
( 'filevskiy-park', 'Филевский Парк', 1, 'Филевском Парке', NULL),
( 'fili-davydkovo', 'Фили-Давыдково', 1, 'Фили-Давыдково', NULL),
( 'hamovniki', 'Хамовники', 1, 'Хамовниках', NULL),
( 'hovrino', 'Ховрино', 1, 'Ховрино', NULL),
( 'horoshevskiy', 'Хорошевский', 1, 'Хорошевском', NULL),
( 'caricyno', 'Царицыно', 1, 'Царицыно', NULL),
( 'cheremushki', 'Черемушки', 1, 'Черемушках', NULL),
( 'chertanovo-severnoe', 'Чертаново Северное', 1, 'Чертаново Северное', NULL),
( 'chertanovo-centralynoe', 'Чертаново Центральное', 1, 'Чертаново Центральное', NULL),
( 'chertanovo-yughnoe', 'Чертаново Южное', 1, 'Чертаново Южное', NULL),
( 'schukino', 'Щукино', 1, 'Щукино', NULL),
( 'yughnoportovyy', 'Южнопортовый', 1, 'Южнопортовый', NULL),
( 'yakimanka', 'Якиманка', 1, 'Якиманки', NULL),
( 'yasenevo', 'Ясенево', 1, 'Ясенево', NULL);"
        );

    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%rayon}}');
    }
}
