<?php

return array(
    'abakan', 'arhangelsk', 'barnaul', 'biysk', 'vladimir', 'volgograd', 'vologda',
    'voronezh', 'gelendzhik', 'ekaterinburg', 'ivanovo', 'izhevsk', 'irkutsk',
    'joshkar-ola', 'kazan', 'kaluga', 'kirov', 'kostroma', 'krasnodar', 'kurgan',
    'kursk', 'lipetsk', 'magnitogorsk', 'murmansk', 'nizhnevartovsk',
    'nizhniy-novgorod', 'nizhniy-tagil', 'novorossiysk', 'omsk', 'penza',
    'petrozavodsk', 'pyatigorsk', 'rostov-na-dony', 'ryazan', 'samara',
    'saratov', 'sevastopol', 'surgut', 'taganrog', 'tver', 'tolyatti',
    'tomsk', 'tumen', 'ulan-ude', 'ulyanovsk', 'ufa', 'habarovsk',
    'cheboksary', 'azov', 'yaroslavl', 'yalta', 'aleksandrov',
    'yakutsk', 'urga', 'ujnosahalinsk', 'aleksin', 'alyshta',
    'engels', 'almetevsk', 'electrougli', 'electrostal',
    'shelkovo', 'amursk', 'anadyir', 'anapa', 'angarsk', 'shahti',
    'shatura', 'shadrinsk', 'chita', 'chehov', 'arzamas', 'armavir',
    'arsenev', 'artyom', 'cherkessk', 'cherepovec', 'astana', 'cheremhovo',
    'ahtubinsk', 'chelyabinsk', 'achinsk', 'chebarkul', 'balakovo', 'balashixa',
    'himki', 'hantimansiysk', 'belebei', 'fryazino', 'fryazevo', 'belogorsk',
    'uhta', 'belokiryxa', 'ustilimsk', 'ussuriyks', 'belorechensk', 'usinsk',
    'berdsk', 'sankt-piterburg', 'berezniki', 'beryozovskiy', 'birobidzhan',
    'blagoveschensk', 'bogorodsk', 'borisoglebsk', 'borovsk', 'bratsk',
    'bronnitsyi', 'bryansk', 'bygylma', 'buzuluk', 'velikie-luki', 'velikiy-novgorod',
    'vidnoe', 'vitebsk', 'vladivostok', 'vladikavkaz', 'volgodansk', 'volzhskiy',
    'volokolamsk', 'volsk', 'vorkuta', 'voskresensk', 'votkinsk', 'vyazma', 'gatchina',
    'georgievsk', 'glasov', 'gomel', 'gorki-leninskie', 'gorno-altaisk', 'goryachiy-klyuch',
    'groznyiy', 'grysi', 'dzerzhinsk', 'dzerzhinskiy', 'dimitrovgrad', 'dinskaya', 'dmitrov',
    'dolgoprudnyiy', 'domodedovo', 'donetsk', 'dybna', 'dyatkovo', 'egorevsk', 'eysk', 'elabyga',
    'elec', 'essentuki', 'zheleznogorsk', 'zheleznogorsk-ilimskiy', 'zheleznodorozhnyiy', 'zhukovka',
    'zhukovskiy', 'zaraysk', 'zvenigorod', 'zelenograd', 'zelenodolsk', 'zlatoust', 'ivanteevka',
    'iskitim', 'istra', 'kamensk-uralskiy', 'kamyishin', 'kanash', 'uray', 'syktyvkar',
    'tuapce', 'troick', 'tobolsk', 'tihoretsk', 'tihvin', 'syzran', 'sudak', 'stupino',
    'ribnoe', 'ribinsk', 'reutov', 'ramenskoe', 'radujniy', 'sosnovyj-bor', 'stavropol',
    'staryj-oskol', 'pushkino', 'pskov', 'protvino', 'prokopievsk', 'pokrov', 'podolsk',
    'pikalevo', 'pechora', 'petropavlovskkamchatskiy', 'solikamsk', 'solnechnogorsk',
    'sorochinsk', 'pavlovskiyposad', 'pavlovsk', 'orsk', 'orehovozuevo', 'olenegorsk',
    'odincovo', 'obninsk', 'nyagan', 'noyabrsk', 'norilsk', 'noginsk', 'noviyurengoy',
    'novomosskovsk', 'magadan', 'salavat', 'salehard', 'saransk', 'satka', 'svobodnyj',
    'seversk', 'severskaja', 'sergiev-posad', 'serpuhov', 'sertolovo', 'sibaj', 'simferopol',
    'smolensk', 'slavjansk-na-kubani', 'maloyaroslavets', 'megion', 'megdurechensk',
    'miass', 'nijnikamsk', 'mineralnie-vodi', 'minusinsk', 'nefteugansk', 'mozdok',
    'mitishchi', 'neftecamsk', 'nerungri', 'nevinomssk', 'nahodka', 'narofominsk',
    'nalchik', 'nadim', 'luberci', 'litkarino', 'luhovitsi', 'luga', 'losino-petrovskiy',
    'lobnya', 'leninogorsk', 'kashira', 'kerch', 'kingisepp', 'kirovsk', 'kislovodsk',
    'klin', 'kovrov', 'kogalim', 'kolomna', 'kolpino', 'komsomolsk-na-amure', 'konakovo',
    'kopeysk', 'korolyov', 'korsakov', 'kotelniki', 'krasnogorsk', 'krasnoe-selo',
    'krimsk', 'kstovo', 'kungur', 'kurilsk', 'kizil'
);