<?php


namespace frontend\widgets;


use common\models\LoginForm;
use yii\authclient\widgets\AuthChoice;
use yii\helpers\Html;
use yii\base\Widget;
use yii\widgets\ActiveForm;

class LoginWidget extends Widget
{
    public function run()
    {

        $login = new LoginForm();

        $form = ActiveForm::begin(['id' => 'login-form',
            'action' => '/login',
            'options' => [
                'class' => 'login-form'
            ]]); ?>

        <div class="login-text">Войти</div>

        <?= $form->field($login, 'email')
        ->textInput(['autofocus' => false, 'placeholder' => 'Email', 'class' => 'form-input email-input'])
        ->label(false) ?>

        <?= $form->field($login, 'password')
        ->passwordInput(['placeholder' => 'Пароль', 'class' => 'form-input pass-input'])
        ->label(false) ?>


        <div class="checbox">
            <?= $form->field($login, 'rememberMe', [
                'template' => "{input} {label} {error}",
            ])->checkbox(['label' => false, 'class' => 'custom-checkbox'])->label('Запомнить меня ', [

            ]) ?>
        </div>
        <?php if (\Yii::$app->requestedParams['city'] == 'moskva') : ?>
        <!-- Yandex.Metrika informer -->
        <a href="https://metrika.yandex.ru/stat/?id=70919698&amp;from=informer"
           target="_blank" rel="nofollow"><img
                    src="https://informer.yandex.ru/informer/70919698/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                    style="width:88px; height:31px; border:0; margin-top: 15px" alt="Яндекс.Метрика"
                    title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"/></a>
        <!-- /Yandex.Metrika informer -->
        <?php endif; ?>

        <div class="login-register-btns">
            <?= Html::submitButton('Войти', ['class' => 'in-btn', 'name' => 'login-button']) ?>
            <a href="#" class="register-btn" onclick="get_register_btn()">Регистрация</a>
        </div>

        <?php if (false) : ?>

        <div class="reset-pass-block">
            <p class="reset-text">
                Забыли пароль <?= Html::a('Сбросить', ['site/request-password-reset']) ?>.
            </p>
            <p class="reset-text">
                Отправить письмо еще раз <?= Html::a('Отправить', ['site/resend-verification-email']) ?>
            </p>

        </div>

    <?php endif; ?>

        <div class="social-in text-center">

            <br>

            <div class="in-with-text">
                Войти с помощью:
            </div>

            <?= AuthChoice::widget([
                'baseAuthUrl' => ['/auth'],
                'popupMode' => false,
            ]) ?>

        </div>


        <?php ActiveForm::end();

        parent::run(); // TODO: Change the autogenerated stub
    }
}